---
title: Configure Security -> BitLocker
description: Configure BitLocker settings
privilege: TrustedInstaller
actions:

  # === Disable Automatic Device Encryption (BitLocker)
  # https://learn.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10#bitlocker-device-encryption
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\BitLocker', value: 'PreventDeviceEncryption', type: REG_DWORD, data: '1'}