---
title: Configure Security
description: Configure security settings
privilege: TrustedInstaller
actions:
  
  # === Hide the Account Protection page in Defender
  # ------> Everything it provides redirects to the Windows Settings anyway. Done for annoyance reduction.
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows Security Health\State', value: 'AccountProtection_MicrosoftAccount_Disconnected', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKU\.DEFAULT\Software\Microsoft\Windows Security Health\State', value: 'AccountProtection_MicrosoftAccount_Disconnected', type: REG_DWORD, data: '0'}

  # ==============================================
  # === Windows Defender Antivirus - Reporting ===
  # ==============================================

  # === Configure Watson events - Disabled
  # ------> https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Reporting', value: 'DisableGenericRePorts', type: REG_DWORD, data: '1'}

  # ==================================================================
  # === Windows Defender Antivirus - Security Intelligence Updates ===
  # ==================================================================

  # === Allow security intelligence updates when running on battery power - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates', value: 'DisableScheduledSignatureUpdateOnBattery', type: REG_DWORD, data: '1'}
  

  # ====================================
  # === Windows Defender SmartScreen ===
  # ====================================

  # === Configure App Install Control - Enabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\SmartScreen', value: 'ConfigureAppInstallControlEnabled', type: REG_DWORD, data: '1'}

  # === Pick one of the following settings - Turn off app recommendations
  # ------> https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.SmartScreen::ConfigureAppInstallControl
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\SmartScreen', value: 'ConfigureAppInstallControl', type: REG_SZ, data: 'Anywhere'}

  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\AppHost', value: 'EnableWebContentEvaluation', type: REG_DWORD, data: '0'}

  # === Configure Windows Defender SmartScreen (Microsoft Edge) - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\MicrosoftEdge\PhishingFilter', value: 'EnabledV9', type: REG_DWORD, data: '0'}

  
  # ========================
  # === Windows Security ===
  # ========================

  # === Hide Windows Security Systray - Enabled
  # ------> https://www.tenforums.com/tutorials/11974-hide-show-windows-security-notification-area-icon-windows-10-a.html
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Systray', value: 'HideSystray', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run', value: 'SecurityHealth', operation: delete}