---
title: Configure Privacy -> Customer Experience Improvement Program (CEIP)
description: Configure CEIP
privilege: TrustedInstaller
actions:
 
  # ------> https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.InternetCommunicationManagement::CEIPEnable
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\SQMClient\Windows', value: 'CEIPEnable', type: REG_DWORD, data: '0'}

  # === App-V
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\AppV\CEIP', value: 'CEIPEnable', type: REG_DWORD, data: '0'}

  # === Internet Explorer Prevent participation in the Customer Experience Improvement Program - Enabled
  # ------> https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.InternetExplorer::SQM_DisableCEIP
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Internet Explorer\SQM', value: 'DisableCustomerImprovementProgram', type: REG_DWORD, data: '1'}

  # === Windows Messenger CEIP
  # ------> https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.InternetCommunicationManagement::WinMSG_NoInstrumentation_1
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Messenger\Client', value: 'CEIP', type: REG_DWORD, data: '2'}

  # === Found in WinSxS
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows NT\CurrentVersion\UnattendSettings\SQMClient', value: 'CEIPEnabled', type: REG_DWORD, data: '0'}
