---
title: Configure Updates -> Microsoft Store
description: Configure Update settings for Microsoft Store
privilege: TrustedInstaller
actions:

  # === Turn off Automatic Download and Install of updates - Disabled
  # ------> https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.WindowsStore::DisableAutoInstall
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\WindowsStore', value: 'AutoDownload', type: REG_DWORD, data: '4'}
  
  # === Turn off the offer to update to the latest version of Windows - Enabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\WindowsStore', value: 'DisableOSUpgrade', type: REG_DWORD, data: '1'}
